### ISSUE TITLE
Create test helpers for downstream projects to use

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/resolution#10]
### Feature request

Add a set of test helpers to `resolution` that projects like Pipelines can use to easily stub / mock `ResourceRequest` objects, `Requester` and `ResolvedResource` implementations,  and errors.

### Use case

Currently Pipelines maintains [its own set of test helpers for stubbing resolution types](https://github.com/sbwsg/pipeline/blob/pipelineref-remote-res/test%2Fresolution.go) and also code for mocking the base64 encoded response to a `ResourceRequest` object: https://github.com/sbwsg/pipeline/blob/pipelineref-remote-res/pkg%2Freconciler%2Fpipelinerun%2Fpipelinerun_test.go#L8770-L8791

It would be great if Pipelines did not have to host this code and instead this kind of test support was available from `resolution` test helpers. Once these helpers are written Pipelines should be updated to use them.

**Comment by abayer** [comment]
Oops, fixed this in #51 but forgot to call it out.
