### ISSUE TITLE
[gitresolver] Switch from git-go git-clone to use providers API

### ISSUE THREAD

**Issue by chmouel** [tektoncd/resolution#42]
### Feature request

On large (mono)?repository, a git clone may take times a lot of time, if we need to just checkin a few files.

It would be nice if we could instead use Git providers (i.e: github/gitlab) APIs instead of checking out the full tree just to grab a few files.

We may along the way will be able to support private repository in gitresolver.

### Use case

Large repository checking,

### Note

- We can just use go-scm to abstract a lot of the naughty different api implementation but the devil may be in the details of each provider.
- User may be able to provider access "token" for auth and ratelimit.
- We can still use anonymous for at least github and maybe other git providers.

**Comment by abayer** [comment]
In practice, we'll probably want to keep the `git` resolver for cases where the user is using a repo that isn't on a supported provider, but it does feel like it'll make sense to add `github`, `gitlab`, etc resolvers to explicitly support credentials, API-driven fetching of individual files, etc.
